version: "3.8"

services:
  mongo-db:
    image: mongo:latest
    restart: always
    container_name: mongo-db
    ports:
      - 27017:27017
    volumes:
      - ./.mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  postgres-db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    container_name: postgres-db
    ports:
      - 5432:5432
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
